# Generated by Django 2.2.8 on 2020-01-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ev_name', models.CharField(max_length=200)),
                ('ev_date', models.DateField()),
                ('ev_time', models.TimeField()),
                ('ev_place', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Facultatives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=200)),
                ('fac_date', models.DateField()),
                ('fac_time', models.TimeField()),
                ('fac_place', models.CharField(max_length=20)),
                ('fac_teacher', models.CharField(max_length=200)),
            ],
        ),
    ]
