# Generated by Django 2.2.8 on 2020-01-09 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0002_events_facultatives'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='Facultatives',
            new_name='Facultative',
        ),
    ]
