# Generated by Django 2.2.8 on 2020-01-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0005_auto_20200109_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_place',
            field=models.CharField(max_length=30),
        ),
    ]
