# Generated by Django 2.2.8 on 2020-01-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0006_auto_20200109_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_place',
            new_name='place',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='time',
        ),
        migrations.RenameField(
            model_name='facultative',
            old_name='facultative_name',
            new_name='info',
        ),
        migrations.RenameField(
            model_name='facultative',
            old_name='facultative_teacher',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='facultative',
            name='facultative_date',
        ),
        migrations.RemoveField(
            model_name='facultative',
            name='facultative_place',
        ),
        migrations.RemoveField(
            model_name='facultative',
            name='facultative_time',
        ),
        migrations.AddField(
            model_name='facultative',
            name='teacher',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
