# Generated by Django 2.2.8 on 2020-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0007_auto_20200128_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('В', 'Востоковедение'), ('E', 'Естественные науки'), ('FL', 'Иностранные языки'), ('C', 'Информатика'), ('RaP', 'Исследовательская и проектная деятельность'), ('H', 'История'), ('HoC', 'История культуры'), ('M', 'Математика'), ('WAC', 'МХК'), ('SC', 'Общественные науки'), ('PS', 'Психология'), ('L', 'Словесность'), ('T', 'ТОК'), ('PE', 'Физическая культура')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='facultative',
            name='department',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
