# Generated by Django 2.2.8 on 2020-01-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0008_auto_20200130_1124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AlterField(
            model_name='facultative',
            name='department',
            field=models.CharField(choices=[('В', 'Востоковедение'), ('E', 'Естественные науки'), ('FL', 'Иностранные языки'), ('C', 'Информатика'), ('RaP', 'Исследовательская и проектная деятельность'), ('H', 'История'), ('HoC', 'История культуры'), ('M', 'Математика'), ('WAC', 'МХК'), ('SC', 'Общественные науки'), ('PS', 'Психология'), ('L', 'Словесность'), ('T', 'ТОК'), ('PE', 'Физическая культура')], max_length=1),
        ),
    ]
