# Generated by Django 2.2.8 on 2020-01-30 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0009_auto_20200130_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='course',
            field=models.CharField(choices=[('В', 'Востоковедение'), ('Г', 'Гуманитарные науки'), ('Д', 'Дизайн'), ('Е', 'Естественные науки'), ('М', 'Математика'), ('И', 'Информатика, инженерия и математика'), ('П', 'Психология'), ('Э', 'Экономика и математика'), ('С', 'Экономика и социальные науки'), ('Ю', 'Юриспруденция')], default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='facultative',
            name='department',
            field=models.CharField(choices=[('В', 'Востоковедение'), ('E', 'Естественные науки'), ('FL', 'Иностранные языки'), ('C', 'Информатика'), ('RaP', 'Исследовательская и проектная деятельность'), ('H', 'История'), ('HoC', 'История культуры'), ('M', 'Математика'), ('WAC', 'МХК'), ('SC', 'Общественные науки'), ('PS', 'Психология'), ('L', 'Словесность'), ('T', 'ТОК'), ('PE', 'Физическая культура')], default=None, max_length=3),
        ),
    ]
