# Generated by Django 2.2.8 on 2020-02-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0012_auto_20200130_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='place',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='info',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
