# Generated by Django 2.2.10 on 2020-02-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpfor9_hse_ru', '0013_auto_20200201_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='job',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='last_name',
        ),
    ]
